name: Release
on:
  workflow_dispatch:
    inputs:
      base-branch:
        description: 'Which branch to create the release from (e.g., master, release-0.8.x)'
        default: 'main'
        required: false
env:
  NODE_VERSION: 14
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.base-branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up semantic-release
        run: npm install conventional-changelog-conventionalcommits

      - name: Release to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.ADVANCED_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: test-bot
          GIT_AUTHOR_EMAIL: test@test.com
          GIT_COMMITTER_NAME: test-bot
          GIT_COMMITTER_EMAIL: test@test.com
        run: npx semantic-release@^17.4.4
